import { Metadata } from "next";
import { ErrorWrapper } from "./error-wrapper";
import { ThemeProvider } from "./comments/theme-provider";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Codevolution",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <header
            style={{
              backgroundColor: "lightblue",
              padding: "1rem",
            }}
          >
            <p>Header</p>
          </header>
          <ErrorWrapper>{children}</ErrorWrapper>
          <footer
            style={{
              backgroundColor: "ghostwhite",
              padding: "1rem",
            }}
          >
            <p>Footer</p>
          </footer>
        </ThemeProvider> 
      </body>
    </html>
  );
}